server:
  port: ${PORT:25985}
  address: 0.0.0.0
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:file:./data/license-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server.error:
  include-message: always
  include-binding-errors: always
  include-exception: false
